### ISSUE TITLE
Did I miss the opportunity to collab with the Chef community on DevOps kung-fu?

### ISSUE THREAD

**Issue by desktophero** [chef/devops-kungfu#161]
I was the 6th PR (a quick look, not scientific!)  submitted to the kung-fu repo. I submitted a variation to the item in the Chef Tao around "scale" which was just sort of deleted. 

https://github.com/chef/devops-kungfu/blob/b215f1ea71d58ff1ce74b741ac1c8bc6702ef225/index.html#L963

Is that enough of a variant to warrant a different fu or if there's a chance to have more convo/explanation on my perspective.

@adamhjk

**Comment by juliandunn** [comment]
@desktophero Adam provided an explanation as to why he closed your PR in the PR itself. https://github.com/chef/devops-kungfu/pull/80

**Comment by desktophero** [comment]
In my haste of looking through closed PRs, I complete blew by it. Thanks for the link @juliandunn; thank you for the details, @adamhjk. Apologies for the stir!
