### ISSUE TITLE
Create a gh-pages branch to publish these slides

### ISSUE THREAD

**Issue by irvingpop** [chef/devops-kungfu#190]
Github pages is awesome.   If we create a `gh-pages` branch (from master) it will publish these slides to http://chef.github.io/devops-kungfu

**Comment by irvingpop** [comment]
To clarify, I'm willing to do this (I have the powah) -  just wondering if anyone things we *shouldn't* do it.

**Comment by ruslanss** [comment]
http://chef.github.io/devops-kungfu is dead (404)

and yeh. defo publish the slides , makes it a lot easier to share

**Comment by juliandunn** [comment]
:+1: @irvingpop

**Comment by irvingpop** [comment]
Done!   The slides are now viewable in all their glory.   Even better, you can directly link to specific slides:  http://chef.github.io/devops-kungfu/#/42

NOTE:  If the slide content gets updated significantly, someone will need to remember to merge the changes into the `gh-pages` branch.

cc: @adamhjk
