### ISSUE TITLE
Is there a discussion area?

### ISSUE THREAD

**Issue by bknowles** [chef/devops-kungfu#210]
So, I've got some questions on how Chef-Style DevOps Kung-Fu might apply in certain circumstances, such as within a professional services organization that is doing work for clients as opposed to product or SaaS development that could/should presumably be shareable with the entire company.

Should that discussion take place here on github somewhere, or is there a different location where that discussion should take place?

**Comment by juliandunn** [comment]
@nathenharvey thoughts on this?

**Comment by nathenharvey** [comment]
If it is a discrete change or addition, I think it should be submitted as a PR in this repo.  If it's a longer form discussion, I think an issue in this repo is the right way to start and we may decide to later encourage discussion on discourse.chef.io.  For now, let's keep as much as possible happening in the repository.

**Comment by bknowles** [comment]
So, the first question I've got relates to doing a demo every week.  I understand the desire, and for internal product/service teams, that makes sense.

But for PSO operations, where you're doing work on behalf of a customer, and you may be the only person at the company who has the clearance and the need-to-know for that information, how do you do a demo?  Do you do that only within the customer side of the equation, as an embedded member of their team?

**Comment by bknowles** [comment]
I guess my next question would be regarding low-velocity organizations -- ones that might want to adopt full devops practices, but which aren't ready yet for the level of instability that can come along with that.

Chef-Style DevOps Kung-Fu tells us something about where the advanced practitioners are and where they're going, but what guidelines might be available to help lower-level organizations get from zero to at least a few steps closer to where the more advanced practitioners are?

**Comment by nathenharvey** [comment]
If you're doing professional services work on behalf of a customer, I would say that you are part of that customer's team and should be participating in their weekly demos.  Our professional services engineers at Chef will do just this.  When the customer hosts a demo day, our engineers will participated and demo the features they've built as part of the team.  

As a professional services consultant or engineer, you are a part of your customer's internal team working toward the delivering features and outcomes for their business or their customers.  GM or AT&T would host the demo days, record them using whatever tech they'd use for that internally, and would be responsible for managing the invite list.

You may also have the opportunity to demo some of the features you've built for your customers with others in your professional services organization and should consider doing that, too.  It will not always be practical to do so though.
