### ISSUE TITLE
Bug in availability formula

### ISSUE THREAD

**Issue by johnsmyth** [chef/devops-kungfu#7]
Availability = uptime/uptime+downtime
should probably be:
Availability = uptime/(uptime+downtime)

**Comment by luntzel** [comment]
+1 for OoO. Nice kung fu.

**Comment by Sauraus** [comment]
+1 for math skills.

**Comment by juliandunn** [comment]
Hey, we'd take a PR! All you have to do is to edit this line. https://github.com/chef/devops-kungfu/blob/master/index.html#L1113

**Comment by juliandunn** [comment]
Fixed in #25
